# Generated by Django 2.2.1 on 2019-05-09 06:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('meaao_site', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walkin',
            name='advisor_id',
        ),
        migrations.RemoveField(
            model_name='walkin',
            name='user_id',
        ),
        migrations.AddField(
            model_name='walkin',
            name='advisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='walkin',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
